export default {
  // Project based actions
  GET_ALL_PROJECTS: 'GET_ALL_PROJECTS',
  CREATE_PROJECT: 'CREATE_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  DELETE_PROJECT_BY_ID: 'DELETE_PROJECT_BY_ID',
  // Users based actions
  CREATE_USER: 'CREATE_USER',
  GET_ALL_USERS: 'GET_ALL_USERS',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER_BY_ID: 'DELETE_USER_BY_ID',
};
